### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by lockeyo** [enesozturk/chatectron#1]
Hi, got this error while running your code. Would be nice if you could look into that problem.

`Couldn't set selectedTextBackgroundColor from default ()
`

**Comment by enesozturk** [comment]
@lockeyo Hi, I'm really sory I'm not taking care of this repo for a long time I don't know why it is not working. I have really no time to look at that. I will notify you if I could do it.

**Comment by enesozturk** [comment]
It' been more that two years 😄 I close the issue. If any body get the same error, that would be good to open new issue. I checked the repo and it working for me. 

Have good coding. 🙌🏽
